pull_request_rules:
  - name: VM6 DUPLICATE POLICY D19U1
    conditions:
      - label = vm6-dup-first-strict-d19u1
    actions:
      comment:
        message: VM6_DUP_FIRST_STRICT
  - name: VM6 DUPLICATE POLICY D19U1
    conditions:
      - label = vm6-dup-second-target-d19u1
    actions:
      comment:
        message: VM6_DUP_SECOND_TARGET
commands_restrictions:
  queue:
    conditions:
      - sender-permission >= write
merge_queue:
  mode: serial
  max_parallel_checks: 1
queue_rules:
  - name: default
    batch_size: 1
    queue_conditions: []
    merge_conditions:
      - check-success = @github-actions/vm6-synthetic-head-delay
    max_checks_retries: 0
    merge_method: merge
    checks_timeout: null
